### ISSUE TITLE
Erro no download linux might 17.3 (Arthur)

### ISSUE THREAD

**Issue by thuzax** [rterrabh/TerraER#21]
comando utilizado na execução: 
            java -jar TerraER2.23.jar 

Erro:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jhotdraw/samples/draw/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)

**Comment by rterrabh** [comment]
Olá. Você está rodando a JDK 8? Teste isso com:
java -version
Me dê o retorno por favor.

**Comment by rterrabh** [comment]
Encerrado por falta de retorno do usuário.
